const { SlashCommandBuilder } = require('@discordjs/builders');
const { MessageEmbed } = require('discord.js');
const { DateTime } = require("luxon");

module.exports = {
    data: new SlashCommandBuilder()
	.setName('avatar')
	.setDescription('Gets the avatar of a user!')
	.addUserOption(option =>
		option.setName('user')
			.setDescription('The user to lookup')),

    async execute(interaction) {

    const User = interaction.options.getUser('user') ?? interaction.user

    const userembed = new MessageEmbed()
    .setTitle("User Lookup")
    .setFooter({text: "Generated by " + interaction.client.user.tag })
    .setColor('DARK_BUT_NOT_BLACK')
    .setTimestamp()
    .setImage(User.displayAvatarURL() + "?size=2048");

    console.log(User.displayAvatarURL())

    await interaction.reply({ embeds: [userembed] });
    },
}