const { SlashCommandBuilder } = require('@discordjs/builders');
const { MessageEmbed } = require('discord.js');
const { DateTime } = require("luxon");

module.exports = {
    data: new SlashCommandBuilder()
	.setName('lookup')
	.setDescription('Gets information about a user!')
	.addUserOption(option =>
		option.setName('user')
			.setDescription('The user to lookup')),

    async execute(interaction) {

    const User = interaction.options.getUser('user') ?? interaction.user
    const loadingembed = new MessageEmbed()
    .setTitle("User Lookup")
    .setDescription(`Looking up ${User.tag} (ID: *${User.id}*)`)
    .setFooter({text: "Generated by " + interaction.client.user.tag })
    .setThumbnail('https://c.tenor.com/I6kN-6X7nhAAAAAj/loading-buffering.gif')
    .setColor('DARK_BUT_NOT_BLACK')
    .setTimestamp();

    const userembed = new MessageEmbed()
    .setTitle(`Information about ${User.tag}`)
    .setDescription(`
    <@${User.id}>
    
    **Username:** ${User.tag}
    
    **ID:** ${User.id} 
    
    **Registration Date:** ${User.createdAt.toLocaleString()} (DD/MM/YYYY)
    
    **Roles:** ${(interaction.options.getMember('user') ?? interaction.member).roles.cache.map(role => role.name).join(", ")}`)
    .setImage(User.bannerURL)
    .setFooter({ text: "Generated by " + interaction.client.user.tag })
    .setThumbnail(User.displayAvatarURL())
    .setColor("DARK_BUT_NOT_BLACK")
    .setTimestamp();

    await interaction.reply({ embeds: [userembed] });
    },
}